export const AUTHORIZE_USER_LOGIN = 'AUTHORIZE_USER_LOGIN';
export const UNAUTHORIZED_LOGIN_ERROR = 'UNAUTHORIZED_LOGIN_ERROR';
export const FETCH_ARTISTS = 'FETCH_ARTISTS';
export const FETCH_ARTIST = 'FETCH_ARTIST';
export const SELECT_ALBUM = 'SELECT_ALBUM';
